version: 2.1

workflows:
    version: 2
    build_and_test:
      jobs:
        - test
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: master

commands:
  install_terraform:
    steps:
    - run: curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.13.7/terraform_0.13.7_linux_amd64.zip
    - run: unzip /tmp/terraform.zip -d /tmp
    - run: mv /tmp/terraform ~/bin
    - run: export PATH="~/bin:$PATH"
  init_terraform:
    steps:
    - run: cd terraform && terraform init -input=false -backend-config="conn_str=$TERRAFORM_BACKEND"

jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make build
      - run: make audit
      - run: make test-ci
      - install_terraform
      - init_terraform
      - run: cd terraform && terraform plan -var app_name=$APP_NAME
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install_terraform
      - run: heroku container:login
      - init_terraform
      - run: cd terraform && terraform apply -input=false -auto-approve -var app_name=$APP_NAME
      - run: docker build -t todos-release --target release --build-arg BACKEND_URL=$BACKEND_URL .
      - run: docker tag todos-release registry.heroku.com/$APP_NAME/web
      - run: docker push registry.heroku.com/$APP_NAME/web
      - run: heroku container:release --app $APP_NAME web